# CLERK AUTHENTICATION
VITE_CLERK_PUBLISHABLE_KEY="pk_test_dG91Y2hlZC1hc3AtNzYuY2xlcmsuYWNjb3VudHMuZGV2JA"

# SUPABASE DATABASE
VITE_APPWRITE_PROJECT_ID = "69fb42c1002aaa636272"
VITE_APPWRITE_PROJECT_NAME = "admin-sakte.id"
VITE_APPWRITE_ENDPOINT = "https://sgp.cloud.appwrite.io/v1"

# DATABASE & BUCKET ID
VITE_APPWRITE_DATABASE_ID=69fb440f00238bac877e
VITE_APPWRITE_BUCKET_ID=69fb4432002e206a5b02

# COLLECTION IDS (ID Tabel)
VITE_APPWRITE_PORTFOLIO_COLLECTION_ID=portofolio
VITE_APPWRITE_SERVICES_COLLECTION_ID=services
VITE_APPWRITE_FAQ_COLLECTION_ID=faq
VITE_APPWRITE_TESTIMONIALS_COLLECTION_ID=testimonials
VITE_APPWRITE_NEBENG_COLLECTION_ID=nebeng_app
